# -*- coding: utf-8 -*-
"""scriptpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13D6Q_jBrxbGvEQ84Brhw1qwVjA2hHVT9
"""

import bz2
from lxml import etree

# Open the bz2 file in binary mode ('rb')
with bz2.open("simplewiki-latest-pages-articles.xml.bz2", 'rb') as f:
    # iterparse expects a file-like object that returns bytes
    # Remove the 'encoding' parameter as it is not needed in binary mode.
    for event, elem in etree.iterparse(f, events=('start',)):
        print("Root tag:", elem.tag)
        break